//! Carbon-project stress test: the domain model exercised with real data
//! from a live carbon-credit registration review (ybird-labs/carbon-project),
//! via committed fixtures generated by `tools/gen_carbon_fixtures.py`.
//!
//! Everything here is user space. The engine (L0 floor, content addressing,
//! L1 validation, projections, snapshots) is used unmodified; the carbon
//! domain brings its own claim-type schemas:
//!
//! - source-evidence: facts about real sites/plots (entity IRIs minted from
//!   farm/plot keys — entity identifiers are claim content; retrieval
//!   coordinates stay in the witnessed SubmissionRecord).
//! - derivation: values derived from other claims by a named rule, citing
//!   input ClaimIRIs in content (`derived_from`).
//! - requirement-judgment: tri-state (`satisfied`/`not_satisfied`/`unclear`)
//!   multi-evidence judgments against numbered registration requirements,
//!   carrying the normative rule version (`credit_class_version`) as content.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use sophia::api::prelude::*;
use sophia::api::term::SimpleTerm;
use sophia::inmem::dataset::LightDataset;

use crate::l0::L0Store;
use crate::l1::{Validator, VALIDATION_RESULT_SCHEMA_IRI};
use crate::projection::l0_projection;
use crate::registry::{SchemaRegistry, SchemaVersion};

pub const SOURCE_EVIDENCE_SCHEMA_IRI: &str =
    "https://carboneg.example/schema/source-evidence/1.0.0";
pub const DERIVATION_SCHEMA_IRI: &str = "https://carboneg.example/schema/derivation/1.0.0";
pub const JUDGMENT_SCHEMA_IRI: &str =
    "https://carboneg.example/schema/requirement-judgment/1.0.0";

/// Ingestion agent for source evidence: appears as the witnessed submitter
/// in SubmissionRecords, never inside claim content.
pub const INGEST_AGENT_IRI: &str = "https://carboneg.example/agent/airtable-ingest";
/// The scripted-checks agent: submits derivations and judgments, and is the
/// asserted `judge` inside judgment content (user-space provenance).
pub const JUDGE_AGENT_IRI: &str = "https://carboneg.example/agent/scripted-site-checks";
/// L1 validator judging carbon claims against their declared schemas.
pub const L1_VALIDATOR_IRI: &str = "https://carboneg.example/agent/l1-validator";

pub fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures_carbon")
}

/// A judgment claim admitted for one (site, requirement) pair.
#[derive(Clone, Debug)]
pub struct CarbonJudgment {
    pub requirement_id: String,
    pub outcome: String,
    pub evidence_iris: BTreeSet<String>,
    pub claim_iri: String,
    /// L1's verdict on the judgment claim itself (validated against the
    /// user-space judgment schema by the unmodified engine machinery).
    pub l1_conforms: bool,
    pub validation_claim_iri: String,
}

/// One real site's worth of admitted claims.
#[derive(Clone, Debug)]
pub struct CarbonSite {
    pub farm_key: String,
    pub site_iri: String,
    pub credit_class_version: String,
    pub judged_at: String,
    /// fixture file name -> ClaimIRI
    pub evidence: BTreeMap<String, String>,
    /// plot evidence ClaimIRI -> real LPIS/GSAA registration id (from fixture)
    pub plot_registrations: BTreeMap<String, String>,
    pub site_record_iri: String,
    pub site_record_resubmission_idempotent: bool,
    pub site_record_submission_count: usize,
    pub derivation_iri: String,
    pub derivation_inputs: BTreeSet<String>,
    pub judgments: Vec<CarbonJudgment>,
}

/// The whole admitted world: two real sites, four requirements each.
pub struct CarbonWorld {
    pub store: L0Store,
    pub registry: SchemaRegistry,
    pub sites: Vec<CarbonSite>,
}

fn read_json(path: &Path) -> serde_json::Value {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

fn str_field<'a>(value: &'a serde_json::Value, field: &str) -> &'a str {
    value[field]
        .as_str()
        .unwrap_or_else(|| panic!("missing string field {field}"))
}

fn register_schema(registry: &mut SchemaRegistry, iri: &str, stem: &str) {
    let dir = fixtures_dir();
    registry
        .register(SchemaVersion {
            iri: iri.to_string(),
            context: read_json(&dir.join(format!("{stem}.context.jsonld"))),
            json_schema: read_json(&dir.join(format!("{stem}.schema.json"))),
        })
        .expect("carbon schema registers");
}

/// Register the three carbon claim-type schemas plus the engine-published
/// validation-result schema (same registration path as the original demo).
pub fn carbon_registry() -> SchemaRegistry {
    let mut registry = SchemaRegistry::new();
    register_schema(&mut registry, SOURCE_EVIDENCE_SCHEMA_IRI, "source-evidence");
    register_schema(&mut registry, DERIVATION_SCHEMA_IRI, "derivation");
    register_schema(&mut registry, JUDGMENT_SCHEMA_IRI, "requirement-judgment");
    registry
        .register(SchemaVersion {
            iri: VALIDATION_RESULT_SCHEMA_IRI.to_string(),
            context: serde_json::from_str(include_str!(
                "../fixtures/validation-result.context.jsonld"
            ))
            .expect("validation-result context fixture"),
            json_schema: serde_json::from_str(include_str!(
                "../fixtures/validation-result.schema.json"
            ))
            .expect("validation-result schema fixture"),
        })
        .expect("register validation-result schema");
    registry
}

/// Build judgment-claim material from plan fields. The credit-class version
/// is an argument so the demo can re-issue the same judgment under a bumped
/// rule version and show it is a different claim.
pub fn judgment_material(
    context: &serde_json::Value,
    plan: &serde_json::Value,
    site_iri: &str,
    judged_at: &str,
    credit_class_version: &str,
    evidence_iris: &BTreeSet<String>,
) -> String {
    serde_json::json!({
        "@context": context["@context"],
        "type": "RequirementJudgment",
        "requirement": str_field(plan, "requirement"),
        "requirement_id": str_field(plan, "requirement_id"),
        "credit_class_version": credit_class_version,
        "site": site_iri,
        "outcome": str_field(plan, "outcome"),
        "evidence": evidence_iris.iter().collect::<Vec<_>>(),
        "judge": JUDGE_AGENT_IRI,
        "judged_at": judged_at,
    })
    .to_string()
}

/// Admit every fixture claim for every site: evidence, then the derivation
/// (whose content cites evidence ClaimIRIs), then the four requirement
/// judgments (whose content cites evidence and derivation ClaimIRIs), each
/// L1-validated against the user-space judgment schema.
pub fn build_world() -> CarbonWorld {
    let dir = fixtures_dir();
    let registry = carbon_registry();
    let mut store = L0Store::new();
    let validator = Validator::new(L1_VALIDATOR_IRI);

    let manifest = read_json(&dir.join("manifest.json"));
    let derivation_context = read_json(&dir.join("derivation.context.jsonld"));
    let judgment_context = read_json(&dir.join("requirement-judgment.context.jsonld"));

    let mut sites = Vec::new();
    for site_entry in manifest["sites"].as_array().expect("manifest sites") {
        let farm_key = str_field(site_entry, "farm_key");
        let site_dir = dir.join("sites").join(farm_key);
        let plan = read_json(&site_dir.join("judgments.json"));
        let site_iri = str_field(&plan, "site").to_string();
        let judged_at = str_field(&plan, "judged_at").to_string();
        let credit_class_version = str_field(&plan, "credit_class_version").to_string();

        // Evidence: admit every .jsonld in the site dir, sorted for
        // determinism. Submitter is the ingest agent — a witnessed fact in
        // the SubmissionRecord, not claim content.
        let mut evidence = BTreeMap::new();
        let mut plot_registrations = BTreeMap::new();
        let mut names: Vec<String> = std::fs::read_dir(&site_dir)
            .expect("site fixture dir")
            .map(|entry| entry.expect("dir entry").file_name().into_string().unwrap())
            .filter(|name| name.ends_with(".jsonld"))
            .collect();
        names.sort();
        for name in names {
            let material = std::fs::read_to_string(site_dir.join(&name)).expect("evidence file");
            let admission = store
                .admit(
                    material.as_bytes(),
                    INGEST_AGENT_IRI,
                    &[SOURCE_EVIDENCE_SCHEMA_IRI],
                    &judged_at,
                )
                .expect("evidence admits through the L0 floor");
            if name.starts_with("plot_") {
                let parsed: serde_json::Value =
                    serde_json::from_str(&material).expect("plot fixture json");
                plot_registrations.insert(
                    admission.claim_iri.clone(),
                    str_field(&parsed, "registration_id").to_string(),
                );
            }
            evidence.insert(name, admission.claim_iri);
        }

        // Idempotent resubmission of the site record (same bytes, second
        // witnessed SubmissionRecord, no second claim).
        let site_record_material =
            std::fs::read_to_string(site_dir.join("site_record.jsonld")).expect("site record");
        let resubmission = store
            .admit(
                site_record_material.as_bytes(),
                INGEST_AGENT_IRI,
                &[SOURCE_EVIDENCE_SCHEMA_IRI],
                &judged_at,
            )
            .expect("resubmission admits");
        let site_record_iri = evidence["site_record.jsonld"].clone();

        // Derivation: the start date is not an authoritative source field;
        // the claim says so structurally, citing its inputs by ClaimIRI.
        let derivation_plan = &plan["derivation"];
        let derivation_inputs: BTreeSet<String> = derivation_plan["inputs"]
            .as_array()
            .expect("derivation inputs")
            .iter()
            .map(|file| evidence[file.as_str().expect("input file name")].clone())
            .collect();
        let derivation_material = serde_json::json!({
            "@context": derivation_context["@context"],
            "type": "Derivation",
            "subject": str_field(derivation_plan, "subject"),
            "property": str_field(derivation_plan, "property"),
            "value": str_field(derivation_plan, "value"),
            "rule": str_field(derivation_plan, "rule"),
            "derived_from": derivation_inputs.iter().collect::<Vec<_>>(),
        })
        .to_string();
        let derivation_iri = store
            .admit(
                derivation_material.as_bytes(),
                JUDGE_AGENT_IRI,
                &[DERIVATION_SCHEMA_IRI],
                &judged_at,
            )
            .expect("derivation admits")
            .claim_iri;

        // Judgments: ordinary claims citing evidence ClaimIRIs, then judged
        // themselves by unmodified L1 against the user-space schema.
        let mut judgments = Vec::new();
        for judgment_plan in plan["judgments"].as_array().expect("judgments") {
            let evidence_iris: BTreeSet<String> = judgment_plan["evidence"]
                .as_array()
                .expect("judgment evidence")
                .iter()
                .map(|entry| match entry.as_str().expect("evidence entry") {
                    "derivation" => derivation_iri.clone(),
                    file => evidence[file].clone(),
                })
                .collect();
            let material = judgment_material(
                &judgment_context,
                judgment_plan,
                &site_iri,
                &judged_at,
                &credit_class_version,
                &evidence_iris,
            );
            let claim_iri = store
                .admit(
                    material.as_bytes(),
                    JUDGE_AGENT_IRI,
                    &[JUDGMENT_SCHEMA_IRI],
                    &judged_at,
                )
                .expect("judgment admits")
                .claim_iri;
            let verdict = validator
                .validate(&mut store, &registry, &claim_iri, JUDGMENT_SCHEMA_IRI, &judged_at)
                .expect("L1 judges the judgment claim");
            judgments.push(CarbonJudgment {
                requirement_id: str_field(judgment_plan, "requirement_id").to_string(),
                outcome: str_field(judgment_plan, "outcome").to_string(),
                evidence_iris,
                claim_iri,
                l1_conforms: verdict.conforms,
                validation_claim_iri: verdict.validation_claim_iri,
            });
        }

        sites.push(CarbonSite {
            farm_key: farm_key.to_string(),
            site_iri,
            credit_class_version,
            judged_at,
            site_record_iri: site_record_iri.clone(),
            site_record_resubmission_idempotent: !resubmission.newly_admitted
                && resubmission.claim_iri == site_record_iri,
            site_record_submission_count: store.submissions_for(&site_record_iri).len(),
            evidence,
            plot_registrations,
            derivation_iri,
            derivation_inputs,
            judgments,
        });
    }

    CarbonWorld {
        store,
        registry,
        sites,
    }
}

/// Objects of `predicate_iri` inside the named graph `graph_iri` of the L0
/// projection — IRIs as IRI strings, literals as lexical values.
pub fn objects_in_graph(
    projection: &LightDataset,
    graph_iri: &str,
    predicate_iri: &str,
) -> BTreeSet<String> {
    let mut objects = BTreeSet::new();
    for quad in projection.quads() {
        let quad = quad.expect("projection quad");
        let in_graph = matches!(
            quad.g(),
            Some(SimpleTerm::Iri(iri)) if iri.as_str() == graph_iri
        );
        let by_predicate = matches!(
            quad.p(),
            SimpleTerm::Iri(iri) if iri.as_str() == predicate_iri
        );
        if in_graph && by_predicate {
            match quad.o() {
                SimpleTerm::Iri(iri) => {
                    objects.insert(iri.as_str().to_string());
                }
                other => {
                    if let Some(lexical) = other.lexical_form() {
                        objects.insert(lexical.to_string());
                    }
                }
            }
        }
    }
    objects
}

/// C4's single SPARQL query: trust composed through a claim chain. Find
/// requirement judgments (asserted content, named graphs) with the given
/// requirement/outcome/judge/rule-version, follow their `evidence` links to
/// claims declaring the source-evidence schema (witnessed metadata, default
/// graph), and read those claims' asserted registration ids (content again).
pub fn judgment_evidence_query(
    requirement_id: &str,
    outcome: &str,
    credit_class_version: &str,
) -> String {
    format!(
        r#"PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rj: <{JUDGMENT_SCHEMA_IRI}/>
PREFIX se: <{SOURCE_EVIDENCE_SCHEMA_IRI}/>
PREFIX ce: <https://claims.example/engine#>
SELECT DISTINCT ?evidence ?registration WHERE {{
  GRAPH ?judgment_graph {{
    ?judgment rdf:type rj:RequirementJudgment ;
              rj:requirement_id "{requirement_id}" ;
              rj:credit_class_version "{credit_class_version}" ;
              rj:outcome "{outcome}" ;
              rj:judge <{JUDGE_AGENT_IRI}> ;
              rj:evidence ?evidence .
  }}
  ?evidence ce:declaresSchema <{SOURCE_EVIDENCE_SCHEMA_IRI}> .
  GRAPH ?evidence {{ ?plot se:registration_id ?registration }}
}}"#
    )
}

/// C5's filter query: judgment ClaimIRIs for a requirement under one
/// specific normative rule version. The version lives in asserted content.
pub fn judgments_by_version_query(requirement_id: &str, credit_class_version: &str) -> String {
    format!(
        r#"PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rj: <{JUDGMENT_SCHEMA_IRI}/>
SELECT DISTINCT ?judgment_claim WHERE {{
  GRAPH ?judgment_claim {{
    ?judgment rdf:type rj:RequirementJudgment ;
              rj:requirement_id "{requirement_id}" ;
              rj:credit_class_version "{credit_class_version}" .
  }}
}}"#
    )
}

/// Re-issue an existing judgment with only the credit-class version changed
/// (a what-if: the checklist moved to a hypothetical next version). Returns
/// the new admission's ClaimIRI.
pub fn reissue_judgment_with_version(
    world: &mut CarbonWorld,
    site_index: usize,
    requirement_id: &str,
    new_version: &str,
) -> String {
    let judgment_context = read_json(&fixtures_dir().join("requirement-judgment.context.jsonld"));
    let site = &world.sites[site_index];
    let plan = read_json(
        &fixtures_dir()
            .join("sites")
            .join(&site.farm_key)
            .join("judgments.json"),
    );
    let judgment_plan = plan["judgments"]
        .as_array()
        .expect("judgments")
        .iter()
        .find(|j| str_field(j, "requirement_id") == requirement_id)
        .expect("requirement in plan");
    let judgment = site
        .judgments
        .iter()
        .find(|j| j.requirement_id == requirement_id)
        .expect("requirement judged");
    let material = judgment_material(
        &judgment_context,
        judgment_plan,
        &site.site_iri,
        &site.judged_at,
        new_version,
        &judgment.evidence_iris,
    );
    world
        .store
        .admit(
            material.as_bytes(),
            JUDGE_AGENT_IRI,
            &[JUDGMENT_SCHEMA_IRI],
            &site.judged_at,
        )
        .expect("re-issued judgment admits")
        .claim_iri
}

/// Expected (evidence ClaimIRI, registration id) pairs for C4, computed from
/// the world — the programmatic counterpart the SPARQL result must equal.
pub fn expected_registration_pairs(
    world: &CarbonWorld,
    requirement_id: &str,
    outcome: &str,
) -> BTreeSet<(String, String)> {
    let mut pairs = BTreeSet::new();
    for site in &world.sites {
        for judgment in &site.judgments {
            if judgment.requirement_id != requirement_id || judgment.outcome != outcome {
                continue;
            }
            for iri in &judgment.evidence_iris {
                if let Some(registration) = site.plot_registrations.get(iri) {
                    pairs.insert((iri.clone(), registration.clone()));
                }
            }
        }
    }
    pairs
}

/// The full L0 projection for the carbon world.
pub fn projection(world: &CarbonWorld) -> LightDataset {
    l0_projection(&world.store).expect("carbon projection builds")
}

const SL_003: &str = "C06-REGISTRATION-SL-003";
const HYPOTHETICAL_NEXT_VERSION: &str = "1.6.0";

fn proof(label: &str, title: &str) {
    println!("\n=== PROOF {label}: {title} ===");
}

fn check(label: &str, condition: bool) {
    assert!(condition, "FAILED: {label}");
    println!("  ok: {label}");
}

/// Narrated carbon demo: asserts proofs C1–C6 and exits nonzero on failure.
pub fn run_demo() {
    use crate::graphdb::SparqlProjection;
    use crate::snapshot::Snapshot;

    println!("Claims Engine spike — carbon-project stress test");
    println!("Real registration-review data: 2 sites, 4 requirements each");
    println!("(fixtures generated from ybird-labs/carbon-project; names pseudonymized)");

    let mut world = build_world();
    check("two real sites admitted", world.sites.len() == 2);

    proof("C1", "real entities admit through the unchanged L0 floor");
    for site in &world.sites {
        let claim = world
            .store
            .claim(&site.site_record_iri)
            .expect("site record claim");
        println!("  site {}: {}", site.farm_key, site.site_record_iri);
        check(
            &format!("{}: entity IRI minted from the real farm key", site.farm_key),
            claim.canonical_nquads().contains(&format!("<{}>", site.site_iri))
                && site.site_iri.ends_with(&site.farm_key),
        );
        check(
            &format!("{}: resubmission is idempotent, both witnessed", site.farm_key),
            site.site_record_resubmission_idempotent && site.site_record_submission_count == 2,
        );
    }
    let floor = world.store.admit(
        b"{\"@context\":{\"p\":\"https://carboneg.example/p\"},\"p\":\"v\"}",
        INGEST_AGENT_IRI,
        &[],
        "2026-05-21T21:31:25+00:00",
    );
    check(
        "the L0 floor still rejects a missing schema declaration",
        floor.is_err(),
    );

    proof("C2", "a derivation claim walks back to its input ClaimIRIs");
    let proj = projection(&world);
    for site in &world.sites {
        let walked = objects_in_graph(
            &proj,
            &site.derivation_iri,
            &format!("{DERIVATION_SCHEMA_IRI}/derived_from"),
        );
        println!(
            "  {}: start date derived from {} input claim(s)",
            site.farm_key,
            walked.len()
        );
        check(
            &format!("{}: derived_from equals the admitted input ClaimIRIs", site.farm_key),
            walked == site.derivation_inputs,
        );
        check(
            &format!("{}: every input claim exists in L0", site.farm_key),
            walked.iter().all(|iri| world.store.claim(iri).is_some()),
        );
    }

    proof("C3", "tri-state multi-evidence judgments are ordinary claims");
    let mut outcomes_seen = BTreeSet::new();
    for site in &world.sites {
        for judgment in &site.judgments {
            let cited = objects_in_graph(
                &proj,
                &judgment.claim_iri,
                &format!("{JUDGMENT_SCHEMA_IRI}/evidence"),
            );
            check(
                &format!(
                    "{} {}: admitted, cites {} evidence claims (≥2) in content",
                    site.farm_key,
                    judgment.requirement_id,
                    cited.len()
                ),
                world.store.claim(&judgment.claim_iri).is_some()
                    && cited == judgment.evidence_iris
                    && cited.len() >= 2,
            );
            check(
                &format!(
                    "{} {}: L1 (unmodified) judges it conformant to the user-space schema",
                    site.farm_key, judgment.requirement_id
                ),
                judgment.l1_conforms
                    && world.store.claim(&judgment.validation_claim_iri).is_some(),
            );
            outcomes_seen.insert(judgment.outcome.clone());
        }
    }
    println!("  outcomes across sites: {outcomes_seen:?}");
    let tri_state: BTreeSet<String> = ["satisfied", "not_satisfied", "unclear"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    check(
        "all three tri-state outcomes occur in the real data",
        outcomes_seen == tri_state,
    );
    let engine_outcomes = world.registry.get(VALIDATION_RESULT_SCHEMA_IRI).unwrap().json_schema
        ["properties"]["outcome"]["enum"]
        .clone();
    check(
        "the engine's own validation vocabulary is untouched (binary)",
        engine_outcomes == serde_json::json!(["conforms", "violations"]),
    );

    proof("C4", "one SPARQL query composes trust through the claim chain");
    let graphdb = SparqlProjection::load(&world.store).expect("projection loads");
    let expected = expected_registration_pairs(&world, SL_003, "satisfied");
    let via_sparql = graphdb
        .select_pairs(
            &judgment_evidence_query(SL_003, "satisfied", &world.sites[0].credit_class_version),
            "evidence",
            "registration",
        )
        .expect("chain query runs");
    println!(
        "  satisfied {SL_003} judgments -> evidence claims -> {} registration ids",
        via_sparql.len()
    );
    check(
        "SPARQL chain result equals the programmatic expectation",
        via_sparql == expected && !expected.is_empty(),
    );
    check(
        "the chain crosses both sites' judgments",
        world.sites.iter().all(|site| {
            site.plot_registrations
                .keys()
                .any(|iri| via_sparql.iter().any(|(evidence, _)| evidence == iri))
        }),
    );

    proof("C5", "the normative rule version is content: bump = new claim");
    let original_iri = world.sites[0]
        .judgments
        .iter()
        .find(|j| j.requirement_id == SL_003)
        .expect("SL-003 judged")
        .claim_iri
        .clone();
    let version = world.sites[0].credit_class_version.clone();
    let reissued_iri =
        reissue_judgment_with_version(&mut world, 0, SL_003, HYPOTHETICAL_NEXT_VERSION);
    println!("  under {version}:  {original_iri}");
    println!("  under {HYPOTHETICAL_NEXT_VERSION}:  {reissued_iri}");
    check(
        "same judgment under a bumped version is a different claim",
        reissued_iri != original_iri,
    );
    check(
        "both versions coexist in L0",
        world.store.claim(&original_iri).is_some() && world.store.claim(&reissued_iri).is_some(),
    );
    let graphdb = SparqlProjection::load(&world.store).expect("projection reloads");
    let under_original: BTreeSet<String> = world
        .sites
        .iter()
        .flat_map(|site| &site.judgments)
        .filter(|j| j.requirement_id == SL_003)
        .map(|j| j.claim_iri.clone())
        .collect();
    let sparql_original = graphdb
        .select_iris(&judgments_by_version_query(SL_003, &version), "judgment_claim")
        .expect("version filter runs");
    let sparql_bumped = graphdb
        .select_iris(
            &judgments_by_version_query(SL_003, HYPOTHETICAL_NEXT_VERSION),
            "judgment_claim",
        )
        .expect("version filter runs");
    check(
        "SPARQL filters judgments by rule version (asserted content)",
        sparql_original == under_original
            && sparql_bumped == [reissued_iri.clone()].into_iter().collect(),
    );

    proof("C6", "an order-independent snapshot over the carbon claims");
    let membership: Vec<String> = world
        .store
        .claims()
        .map(|claim| claim.iri().to_string())
        .collect();
    let forward = Snapshot::create(membership.iter().cloned()).expect("snapshot builds");
    let reverse = Snapshot::create(membership.iter().rev().cloned()).expect("snapshot builds");
    println!(
        "  snapshot over {} claims: {}",
        forward.membership().len(),
        forward.iri()
    );
    check(
        "membership order does not affect fingerprint or IRI",
        forward.fingerprint() == reverse.fingerprint() && forward.iri() == reverse.iri(),
    );

    println!("\nPASS C1: real entities admit through the unchanged L0 floor");
    println!("PASS C2: derivation claims walk back to their input ClaimIRIs");
    println!("PASS C3: tri-state multi-evidence judgments are ordinary claims");
    println!("PASS C4: one SPARQL query composes trust through the claim chain");
    println!("PASS C5: rule versions are content — a bump is a new claim");
    println!("PASS C6: snapshot fingerprints are order-independent");
    println!("\nALL CARBON PROOFS PASSED");
}
